USE League_Database;
DROP TABLE awards;
DROP TABLE stats;
DROP TABLE results;
DROP TABLE matches;
DROP TABLE tournaments;
DROP TABLE contracts;
DROP TABLE transfers;
DROP TABLE players;
DROP TABLE coaches;
DROP TABLE teams;
DROP TABLE leagues;